function onLoad()
  self.setLock(true)
  self.setRotation(Vector(0,180,0))
  self.setPosition(Vector(0,1,0)) -- your whole play area should be at or above y=1! A card placed on this surface will be at y=2.01
  self.interactable = false -- comment this out to interact
  self.drag_selectable = false -- change to true to allow it to be drag selected (only if the above line is also true)
  self.gizmo_selectable = false -- change this to true to allow the gizmo tool to interact with it
end
